### ISSUE TITLE
Spaces in path not handled on Linux

### ISSUE THREAD

**Issue by ghost** [exjam/excmd#1]
For example:

./src/decaf-emu play /home/game\ folder

Results in:
Could not find file or directory /home/game

**Comment by exjam** [comment]
Ah thanks, I forgot about whitespace escaping!

**Comment by exjam** [comment]
Wait a sec... on Linux we use argc, argv in which case this should be handled by your shell? I will investigate..

**Comment by exjam** [comment]
Ah caught it, was caused by this:

https://github.com/exjam/excmd/commit/7e4f6f55d98d1ed60bac13afa9dd1f57235afc63

Thanks!
